services:
  postgres:
    image: postgres:16-alpine
    container_name: drivealbum_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: drivealbum
      POSTGRES_PASSWORD: drivealbum_secret
      POSTGRES_DB: drivealbum_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

